### ISSUE TITLE
请问下使用MFA对齐后，文本预处理的流程是怎么样的？

### ISSUE THREAD

**Issue by LainNya** [innnky/vispeech#5]

**Comment by innnky** [comment]
目前我这边预处理的流程比较混乱，因为是一遍摸索一遍改的代码的，，大致基本就是fastspeech2的流程，提取frame级f0和energy，再根据mfa音素时长计算音素级f0和energy（energy相关代码我还没push）最后把所有预处理的数据全写在filelists里。总之制作数据集挺繁琐的目前，，感觉换来的效果提升也没有特别显著

**Comment by innnky** [comment]
就文本来说的话，mfa对齐后的音素序列就是模型的输入（转换为音素id后输入）

**Comment by LainNya** [comment]
就是说使用fastspeech2内的预处理方法拿到phones和durations,然后使用extract_f0生成吗？

**Comment by innnky** [comment]
大致是这样，有个temp.py是计算音素级平均f0的，其实还有几个预处理脚本没push上来，目前还是比较混乱的，如果整体效果满意了我应该会尽可能整合做一个一键的数据集制作流程，但就目前而言预处理的话还是相当折腾的

**Comment by LainNya** [comment]
好的，感谢解惑

**Comment by makerjackie** [comment]
> 目前我这边预处理的流程比较混乱，因为是一遍摸索一遍改的代码的，，大致基本就是fastspeech2的流程，提取frame级f0和energy，再根据mfa音素时长计算音素级f0和energy（energy相关代码我还没push）最后把所有预处理的数据全写在filelists里。总之制作数据集挺繁琐的目前，，感觉换来的效果提升也没有特别显著

我看论文是这么操作能够降低 WER，我的经验是 vits 多人数据（内部数据）训练600k步前WER都比较高
