### ISSUE TITLE
revert separate tone symbol 是因为效果不好吗?

### ISSUE THREAD

**Issue by makerjackie** [innnky/vispeech#6]
https://github.com/innnky/vispeech/commit/f75291c9a4faadf131d58578d6f6c56dbf172a31

我自己也做过类似的实验，在vits中，声调和韵母分开后，咬字没那么清晰

**Comment by innnky** [comment]
咬字倒还好，但主要是分开后感觉语调似乎反而似乎没原来的好了，所以就退回去了。
